---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iyjys386eqbq/public_html/
    - /bin/cp dist/index.html $DEPLOYPATH
    - /bin/cp -R dist/assets $DEPLOYPATH
    - /bin/cp dist/*.png $DEPLOYPATH
    - /bin/cp dist/*.jpg $DEPLOYPATH
    - /bin/cp dist/*.svg $DEPLOYPATH
